[2023-06-26T06:31:29.668+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: execute_python.check_participants manual__2023-06-26T04:30:13.590801+00:00 [queued]>
[2023-06-26T06:31:29.674+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: execute_python.check_participants manual__2023-06-26T04:30:13.590801+00:00 [queued]>
[2023-06-26T06:31:29.674+0200] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2023-06-26T06:31:29.690+0200] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): check_participants> on 2023-06-26 04:30:13.590801+00:00
[2023-06-26T06:31:29.693+0200] {standard_task_runner.py:57} INFO - Started process 100772 to run task
[2023-06-26T06:31:29.695+0200] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'execute_python', 'check_participants', 'manual__2023-06-26T04:30:13.590801+00:00', '--job-id', '90', '--raw', '--subdir', 'DAGS_FOLDER/thesis_container.py', '--cfg-path', '/tmp/tmpmu6klo1t']
[2023-06-26T06:31:29.696+0200] {standard_task_runner.py:85} INFO - Job 90: Subtask check_participants
[2023-06-26T06:31:29.734+0200] {task_command.py:410} INFO - Running <TaskInstance: execute_python.check_participants manual__2023-06-26T04:30:13.590801+00:00 [running]> on host DESKTOP-3KJU1M7.
[2023-06-26T06:31:29.786+0200] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='execute_python' AIRFLOW_CTX_TASK_ID='check_participants' AIRFLOW_CTX_EXECUTION_DATE='2023-06-26T04:30:13.590801+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-26T04:30:13.590801+00:00'
[2023-06-26T06:31:29.787+0200] {logging_mixin.py:149} INFO - ['reynel_95']
[2023-06-26T06:31:29.787+0200] {logging_mixin.py:149} INFO - []
[2023-06-26T06:31:29.787+0200] {logging_mixin.py:149} INFO - ['reynel_95']
[2023-06-26T06:31:29.787+0200] {logging_mixin.py:149} INFO - New participants found. Creating containers...
[2023-06-26T06:31:29.787+0200] {logging_mixin.py:149} INFO - 0
[2023-06-26T06:31:29.787+0200] {logging_mixin.py:149} INFO - <class 'int'>
[2023-06-26T06:31:29.787+0200] {logging_mixin.py:149} INFO - ['reynel_95']
[2023-06-26T06:31:29.787+0200] {logging_mixin.py:149} INFO - list test ['reynel_95']
[2023-06-26T06:31:29.788+0200] {logging_mixin.py:149} INFO - ['/home/reynel1995/Thesis/Participant1/1_6-6.mrxs']
[2023-06-26T06:31:29.788+0200] {logging_mixin.py:149} INFO - single container reynel_95
[2023-06-26T06:31:29.788+0200] {logging_mixin.py:149} INFO - /home/reynel1995/Thesis/Participant1/1_6-6.mrxs
[2023-06-26T06:31:29.788+0200] {logging_mixin.py:149} INFO - /home/reynel1995/Thesis/Participant1/1_6-6.mrxs
[2023-06-26T06:31:29.788+0200] {logging_mixin.py:149} INFO - /home/reynel1995/Thesis/Participant1
[2023-06-26T06:31:29.788+0200] {logging_mixin.py:149} INFO - ['/home/reynel1995/Thesis/Participant1/1_6-6.mrxs']
[2023-06-26T06:31:33.075+0200] {logging_mixin.py:149} INFO - Container 1_6-6.mrxs image built successfully.
[2023-06-26T06:31:34.632+0200] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/reynel1995/thesis/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/reynel1995/thesis/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/reynel1995/airflow/dags/thesis_container.py", line 263, in check_participants
    build_and_run_containers(index)
  File "/home/reynel1995/airflow/dags/thesis_container.py", line 121, in build_and_run_containers
    subprocess.run(run_command, shell=True, check=True)
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'docker run -d --name 1_6-6.mrxs 1_6-6.mrxs' returned non-zero exit status 125.
[2023-06-26T06:31:34.636+0200] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=execute_python, task_id=check_participants, execution_date=20230626T043013, start_date=20230626T043129, end_date=20230626T043134
[2023-06-26T06:31:34.649+0200] {standard_task_runner.py:104} ERROR - Failed to execute job 90 for task check_participants (Command 'docker run -d --name 1_6-6.mrxs 1_6-6.mrxs' returned non-zero exit status 125.; 100772)
[2023-06-26T06:31:34.654+0200] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-26T06:31:34.696+0200] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
